use crate::models::BetSection;
use std::path::Path;

/// Generate the spec/README.md overview file.
pub fn generate_readme(output_path: &Path, project_name: &str, sections: &[BetSection]) {
    let required_count = sections.iter().filter(|s| s.required).count();
    let optional_count = sections.iter().filter(|s| !s.required).count();
    let included_optional = sections.iter().filter(|s| !s.required && s.included).count();

    let mut section_list = String::new();
    for s in sections {
        let status = if s.included { "[x]" } else { "[ ]" };
        let tag = if s.required { "REQUIRED" } else { "OPTIONAL" };
        section_list.push_str(&format!(
            "- {} **{}** ({}) — {}\n",
            status, s.filename, tag, s.description
        ));
    }

    let content = format!(
        r#"# {project_name} — BET Spec

Generated by [bet](https://github.com/doomedramen/BET).

## Project Summary

- **Project**: {project_name}
- **Sections included**: {total_included} ({required_count} required + {optional_included} optional)
- **Sections skipped**: {skipped}

## Structure

```
spec/
{sections}
```

## How to Use

1. Read `docs/FORMAT.md` for writing conventions
2. Fill in sections following the recommended order
3. Use `docs/GUIDE.md` for tips on each section
4. Validate with `docs/COMPLETENESS-CHECKLIST.md`
5. Generate BDD scenarios using `docs/BDD-GENERATION.md`

## Recommended Fill-in Order

1. Capabilities → 2. Data Model → 3. Permissions → 4. Validation → 5. Business Rules → 6. Flow/State → 7. Conditional Logic → 8. Constraints → 9. External → 10. Events → 11. Messages → 12. Errors → 13. Edge Cases → 14. Dependencies → 15. Non-Functional → 16. Interaction → 17. Accessibility → 18. Data Lifecycle → 19-26. Optional Extensions

"#,
        project_name = project_name,
        total_included = required_count + included_optional,
        required_count = required_count,
        optional_included = included_optional,
        skipped = optional_count - included_optional,
        sections = section_list.trim_end(),
    );

    std::fs::write(output_path.join("README.md"), content).expect("Failed to write README.md");
}
