use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct BetSection {
    pub number: u8,
    pub name: String,
    pub filename: String,
    pub required: bool,
    pub description: String,
    pub included: bool,
}

pub fn all_sections() -> Vec<BetSection> {
    vec![
        BetSection {
            number: 1,
            name: "Capabilities".to_string(),
            filename: "01-capabilities.md".to_string(),
            required: true,
            description: "System goals and actors — what the system does and who uses it".to_string(),
            included: true,
        },
        BetSection {
            number: 2,
            name: "Data Model".to_string(),
            filename: "02-data-model.md".to_string(),
            required: true,
            description: "Entities, fields, types, ownership, transformations".to_string(),
            included: true,
        },
        BetSection {
            number: 3,
            name: "Permissions".to_string(),
            filename: "03-permissions.md".to_string(),
            required: false,
            description: "Roles and access control — who can do what".to_string(),
            included: false,
        },
        BetSection {
            number: 4,
            name: "Validation Rules".to_string(),
            filename: "04-validation-rules.md".to_string(),
            required: true,
            description: "Input correctness rules — format, presence, range checks".to_string(),
            included: true,
        },
        BetSection {
            number: 5,
            name: "Business Rules".to_string(),
            filename: "05-business-rules.md".to_string(),
            required: true,
            description: "Core logic, decisions, presentation rules (sort/filter)".to_string(),
            included: true,
        },
        BetSection {
            number: 6,
            name: "Flow / State".to_string(),
            filename: "06-flow-state.md".to_string(),
            required: true,
            description: "States, transitions, resumability — how the system progresses".to_string(),
            included: true,
        },
        BetSection {
            number: 7,
            name: "Conditional Logic".to_string(),
            filename: "07-conditional-logic.md".to_string(),
            required: true,
            description: "Dynamic behaviour, cascades, field visibility".to_string(),
            included: true,
        },
        BetSection {
            number: 8,
            name: "Constraints".to_string(),
            filename: "08-constraints.md".to_string(),
            required: true,
            description: "Blocking conditions, recovery, rate limits".to_string(),
            included: true,
        },
        BetSection {
            number: 9,
            name: "External Interactions".to_string(),
            filename: "09-external-interactions.md".to_string(),
            required: false,
            description: "APIs, services, failure modes, API contracts".to_string(),
            included: false,
        },
        BetSection {
            number: 10,
            name: "Events & Side Effects".to_string(),
            filename: "10-events-side-effects.md".to_string(),
            required: false,
            description: "Analytics, webhooks, notifications, audit logs".to_string(),
            included: false,
        },
        BetSection {
            number: 11,
            name: "Messages".to_string(),
            filename: "11-messages.md".to_string(),
            required: true,
            description: "All user-facing text: errors, help, legal, content".to_string(),
            included: true,
        },
        BetSection {
            number: 12,
            name: "Error Taxonomy".to_string(),
            filename: "12-error-taxonomy.md".to_string(),
            required: false,
            description: "Error categories, retry logic, fallback strategies".to_string(),
            included: false,
        },
        BetSection {
            number: 13,
            name: "Edge Cases".to_string(),
            filename: "13-edge-cases.md".to_string(),
            required: true,
            description: "What could go wrong: data, timing, concurrency, multi-session".to_string(),
            included: true,
        },
        BetSection {
            number: 14,
            name: "Dependencies".to_string(),
            filename: "14-dependencies.md".to_string(),
            required: false,
            description: "Prerequisites, assumptions, seed data".to_string(),
            included: false,
        },
        BetSection {
            number: 15,
            name: "Non-Functional".to_string(),
            filename: "15-non-functional.md".to_string(),
            required: false,
            description: "Performance, availability, retention".to_string(),
            included: false,
        },
        BetSection {
            number: 16,
            name: "Interaction Behaviour".to_string(),
            filename: "16-interaction-behaviour.md".to_string(),
            required: true,
            description: "Error display, loading, auto-save, navigation".to_string(),
            included: true,
        },
        BetSection {
            number: 17,
            name: "Accessibility".to_string(),
            filename: "17-accessibility.md".to_string(),
            required: true,
            description: "Keyboard nav, focus management, screen readers, WCAG".to_string(),
            included: true,
        },
        BetSection {
            number: 18,
            name: "Data Lifecycle".to_string(),
            filename: "18-data-lifecycle.md".to_string(),
            required: true,
            description: "Consent, retention, deletion, compliance".to_string(),
            included: true,
        },
        BetSection {
            number: 19,
            name: "UI Specification".to_string(),
            filename: "19-ui-specification.md".to_string(),
            required: false,
            description: "Visual design, layout, components, responsive behaviour".to_string(),
            included: false,
        },
        BetSection {
            number: 20,
            name: "Technical Architecture".to_string(),
            filename: "20-technical-architecture.md".to_string(),
            required: false,
            description: "Stack, database, API design, infrastructure".to_string(),
            included: false,
        },
        BetSection {
            number: 21,
            name: "SEO".to_string(),
            filename: "21-seo.md".to_string(),
            required: false,
            description: "URLs, metadata, indexing, social sharing".to_string(),
            included: false,
        },
        BetSection {
            number: 22,
            name: "Localization".to_string(),
            filename: "22-localization.md".to_string(),
            required: false,
            description: "Dates, currency, numbers, locale support".to_string(),
            included: false,
        },
        BetSection {
            number: 23,
            name: "Animation".to_string(),
            filename: "23-animation.md".to_string(),
            required: false,
            description: "Transitions, micro-interactions, motion preferences".to_string(),
            included: false,
        },
        BetSection {
            number: 24,
            name: "Monitoring".to_string(),
            filename: "24-monitoring.md".to_string(),
            required: false,
            description: "Dashboards, alerts, logging, health checks".to_string(),
            included: false,
        },
        BetSection {
            number: 25,
            name: "Onboarding".to_string(),
            filename: "25-onboarding.md".to_string(),
            required: false,
            description: "First-run, empty states, feature discovery".to_string(),
            included: false,
        },
        BetSection {
            number: 26,
            name: "Multi-Channel".to_string(),
            filename: "26-multi-channel.md".to_string(),
            required: false,
            description: "Cross-device, cross-platform behaviour".to_string(),
            included: false,
        },
        BetSection {
            number: 27,
            name: "Testing Strategy".to_string(),
            filename: "27-testing-strategy.md".to_string(),
            required: false,
            description: "Test layers, frameworks, coverage plan, known gaps".to_string(),
            included: false,
        },
    ]
}
